auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: millerZZS.github.io
url: http://millerZZS.github.io
feed: /atom.xml
author_info: <a href="http://millerZZS.github.io">millerzzs</a>
